import os
from dotenv import load_dotenv

load_dotenv()

HF_READ_TOKEN = os.getenv('HF_READ_TOKEN')
HF_WRITE_TOKEN = os.getenv('HF_WRITE_TOKEN')

RAW_EDITORIAL_URLS_PATH = os.getenv('RAW_EDITORIAL_URLS_PATH')
CLEAN_EDITORIAL_URLS_PATH = os.getenv('CLEAN_EDITORIAL_URLS_PATH')

EDITORIAL_CONTENT_PATH = os.getenv('EDITORIAL_CONTENT_PATH')
EDITORIAL_CONTENT_FAIL_PATH = os.getenv('EDITORIAL_CONTENT_FAIL_PATH')
EDITORIAL_TO_REVIEW_PATH = os.getenv('EDITORIAL_TO_REVIEW_PATH')

CLEAN_EDITORIAL_CONTENT_PATH = os.getenv('CLEAN_EDITORIAL_CONTENT_PATH')

PROBLEM_URLS_PATH = os.getenv('PROBLEM_URLS_PATH')

GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY')

EDITORIAL_DATASET = os.getenv('EDITORIAL_DATASET')
GENERATOR_MODEL_ID = os.getenv('GENERATOR_MODEL_ID')

MONGO_USER = os.getenv('MONGO_USER')
MONGO_PASSWORD = os.getenv('MONGO_PASSWORD')