import os
from dotenv import load_dotenv

load_dotenv()

HF_READ_TOKEN = os.getenv('HF_READ_TOKEN')

RAW_EDITORIAL_URLS_PATH = os.getenv('RAW_EDITORIAL_URLS_PATH')
CLEAN_EDITORIAL_URLS_PATH = os.getenv('CLEAN_EDITORIAL_URLS_PATH')

EDITORIAL_CONTENT_PATH = os.getenv('EDITORIAL_CONTENT_PATH')
EDITORIAL_CONTENT_FAIL_PATH = os.getenv('EDITORIAL_CONTENT_FAIL_PATH')
EDITORIAL_TO_REVIEW_PATH = os.getenv('EDITORIAL_TO_REVIEW_PATH')

CLEAN_EDITORIAL_CONTENT_PATH = os.getenv('CLEAN_EDITORIAL_CONTENT_PATH')

PROBLEM_URLS_PATH = os.getenv('PROBLEM_URLS_PATH')
