CREATE TABLE problems (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  description TEXT NOT NULL,
  public_tests JSONB NOT NULL,
  private_tests JSONB NOT NULL,
  generated_tests JSONB NOT NULL,
  source INT NOT NULL,
  difficulty INT NOT NULL,
  solutions JSONB NOT NULL,
  incorrect_solutions JSONB NOT NULL,
  cf_contest_id INT NOT NULL,
  cf_index VARCHAR(255) NOT NULL,
  cf_points FLOAT NOT NULL,
  cf_rating INT NOT NULL,
  cf_tags text[] NOT NULL,
  is_description_translated BOOLEAN NOT NULL,
  untranslated_description TEXT NOT NULL,
  time_limit JSONB,
  memory_limit_bytes INT NOT NULL,
  input_file TEXT NOT NULL,
  output_file TEXT NOT NULL,
  editorial TEXT NOT NULL
);